# Generated by Django 3.1.7 on 2021-03-21 14:14

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Park',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('park_id', models.IntegerField(null=True)),
                ('park_name', models.CharField(max_length=255, null=True)),
                ('lat', models.FloatField(null=True)),
                ('lng', models.FloatField(null=True)),
                ('capacity', models.IntegerField(null=True)),
                ('empty_capacity', models.IntegerField(null=True)),
                ('work_hours', models.CharField(max_length=255, null=True)),
                ('park_type', models.CharField(max_length=255, null=True)),
                ('free_time', models.IntegerField(null=True)),
                ('district', models.CharField(max_length=255, null=True)),
                ('is_open', models.IntegerField(null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, default='POINT(0.0 0.0)', srid=4326)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Parklar',
            },
        ),
    ]
