# Generated by Django 3.1.7 on 2021-03-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='park',
            name='park_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Park Adı'),
        ),
    ]
