# Generated by Django 3.1.7 on 2021-03-21 14:22

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkapp', '0002_auto_20210321_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='park',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, default='POINT(0.0 0.0)', srid=4326, verbose_name='Konum'),
        ),
    ]
